#!/usr/bin/env bash
# SPDX-License-Identifier: AGPL-3.0-or-later
#MISE description="Run end-to-end tests"
#MISE depends=["build:dev"]
#MISE dir="tests/e2e"
set -euo pipefail

export SHARKFIN_BINARY="${MISE_PROJECT_ROOT}/build/sharkfin"
go test -v -race -timeout 180s ./...
